import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowRight, BarChart3, Bell, Bot, BriefcaseBusiness, Check, CheckCircle2, ChevronRight,
  CircleDot, Globe2, Headphones, Home, LayoutTemplate, Leaf, MapPin, Menu, MessageSquareText, Mic2,
  PenLine, Play, RotateCcw, Search, Send, Sparkles, Target, TrendingUp, Users, X, Zap,
  DollarSign, ShieldCheck, Rocket, Layers3, UserRoundCheck, Workflow,
} from 'lucide-react'
import { cleanDhakaActivity, getWorker, metrics, problems, tutorialDefaults, tutorialRecommendation, workers, workspaces, type Worker, type WorkerId } from './data'

type View = 'overview' | 'workers' | 'workspaces' | 'workspace' | 'impact' | 'tutorial' | 'investor'
const nav: {id:View; label:string; icon:typeof Home}[] = [
  {id:'overview',label:'Overview',icon:Home},{id:'workers',label:'AI Workers',icon:Bot},
  {id:'workspaces',label:'Demo Workspaces',icon:BriefcaseBusiness},{id:'impact',label:'Bangladesh Impact',icon:Leaf},
  {id:'tutorial',label:'Workforce Tutorial',icon:Sparkles},
  {id:'investor',label:'Investor View',icon:Rocket},
]
const iconMap: Record<WorkerId, typeof Bot> = {content:PenLine,campaign:Send,service:Headphones,landing:LayoutTemplate,success:Users,growth:TrendingUp,voice:Mic2}

function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'cyan'|'green'|'amber'|'purple'}) {
  return <span className={`badge ${tone}`}><span className="badge-dot"/>{children}</span>
}

function SectionHeader({eyebrow,title,copy,action}:{eyebrow?:string;title:string;copy?:string;action?:React.ReactNode}) {
  return <header className="section-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{action}</header>
}

function WorkerIcon({worker,size='md'}:{worker:Worker;size?:'sm'|'md'|'lg'}) {
  const Icon=iconMap[worker.id]
  return <span className={`worker-icon ${size}`} style={{'--accent':worker.accent} as React.CSSProperties}><Icon/></span>
}

function Sidebar({view,setView,open,setOpen}:{view:View;setView:(v:View)=>void;open:boolean;setOpen:(v:boolean)=>void}) {
  const go=(v:View)=>{setView(v);setOpen(false)}
  return <><div className={`scrim ${open?'show':''}`} onClick={()=>setOpen(false)}/><aside className={`sidebar ${open?'open':''}`}>
    <div className="brand" onClick={()=>go('overview')}><span className="brand-mark"><Zap/></span><span>AI Workforce <b>Hub</b></span></div>
    <div className="side-label">WORKSPACE</div>
    <nav aria-label="Primary navigation">{nav.map(item=><button key={item.id} className={view===item.id||view==='workspace'&&item.id==='workspaces'?'active':''} onClick={()=>go(item.id)}><item.icon/><span>{item.label}</span>{view===item.id&&<span className="active-pip"/>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="prototype-card"><span className="live-dot"/><strong>Prototype mode</strong><p>All activity and metrics are simulated locally.</p></div><p className="version">HACK FOR HUMANITY • 2026</p></div>
  </aside></>
}

function TopBar({setMenu}:{setMenu:(v:boolean)=>void}) {
  return <div className="topbar"><button className="icon-btn menu-btn" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><div className="top-spacer"/><Badge tone="purple">Hack for Humanity 2026</Badge><Badge tone="cyan">Demo mode</Badge><button className="icon-btn" aria-label="Activity notifications"><Bell/><span className="notify-dot"/></button><div className="avatar"><span>DT</span><div><b>Demo Team</b><small>Prototype access</small></div></div></div>
}

function Overview({go}:{go:(v:View)=>void}) {
  return <div className="page overview-page">
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/>A coordinated digital workforce</div><h1>Meet the AI workforce built to help organizations <span>operate, serve, and grow.</span></h1><p>Seven specialized AI workers collaborate across content, campaigns, customer service, voice support, digital experiences, customer success, and growth analysis.</p><div className="hero-actions"><button className="primary" onClick={()=>go('workers')}>Explore AI Workers <ArrowRight/></button><button className="secondary" onClick={()=>go('impact')}>See Bangladesh Impact Demo</button></div><small>Frontend prototype — all organizations and metrics shown here are demo data.</small></div>
      <div className="constellation" aria-label="AI workforce constellation"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hub-node"><span><Zap/></span><b>WORKFORCE<br/>HUB</b><small>COORDINATING</small></div>{workers.map((w,i)=><div className={`orbit-worker ow-${i+1}`} key={w.id}><WorkerIcon worker={w} size="sm"/><span>{w.shortName}</span></div>)}<div className="signal signal-one"/><div className="signal signal-two"/></div>
    </section>
    <section className="worker-strip">{workers.map(w=><button key={w.id} onClick={()=>go('workers')}><WorkerIcon worker={w} size="sm"/><span>{w.shortName}</span></button>)}</section>
    <section className="three-steps"><div className="eyebrow">HOW IT WORKS</div><div className="steps-grid">{[['01','Describe a challenge','Share the organization, context, and desired human outcome.'],['02','Activate the right workers','Coordinate a focused team for the workflow.'],['03','Measure human impact','Review prototype insights with people in control.']].map((s,i)=><article key={s[0]}><span className="step-no">{s[0]}</span><div className="step-icon">{i===0?<MessageSquareText/>:i===1?<Sparkles/>:<BarChart3/>}</div><h3>{s[1]}</h3><p>{s[2]}</p>{i<2&&<ArrowRight className="step-arrow"/>}</article>)}</div></section>
    <section className="preview-card"><div><Badge tone="green">Featured demo workspace</Badge><h2>See coordinated response in action.</h2><p>Explore how a simulated AI workforce could help a Dhaka waste-service team turn a resident voice complaint into a structured, bilingual, human-approved response.</p><button className="text-button" onClick={()=>go('workspace')}>Open CleanDhaka Response Hub <ArrowRight/></button></div><div className="mini-workspace"><div className="mini-top"><span className="mini-logo">CD</span><div><b>CleanDhaka Services</b><small>Mirpur, Dhaka • Demo workspace</small></div><Badge tone="green">Active demo</Badge></div><div className="mini-issue"><Mic2/><div><small>INCOMING VOICE REPORT</small><p>“Waste has not been collected for three days...”</p></div></div><div className="mini-team">{['voice','service','growth','success'].map((id,i)=><div key={id} style={{animationDelay:`${i*.25}s`}}><Check/>{getWorker(id as WorkerId).shortName}</div>)}</div></div></section>
    <section className="statement"><span className="quote-mark">“</span><p>We build human-centered AI systems that turn complex business and civic workflows into coordinated, measurable action.</p><span>AI WORKFORCE HUB • PRODUCT PRINCIPLE</span></section>
  </div>
}

function WorkerCard({worker,onOpen}:{worker:Worker;onOpen:()=>void}) {return <article className="worker-card"><div className="card-top"><WorkerIcon worker={worker}/><Badge tone="green">Available</Badge></div><h3>{worker.name}</h3><p>{worker.description}</p><div className="tags">{worker.tags.map(t=><span key={t}>{t}</span>)}</div><button className="card-button" onClick={onOpen}>View Worker <ArrowRight/></button></article>}

function WorkerModal({worker,onClose,onActivate}:{worker:Worker;onClose:()=>void;onActivate:()=>void}) {
  const Icon=iconMap[worker.id]
  useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[onClose])
  return <div className="modal-wrap" role="dialog" aria-modal="true" aria-labelledby="worker-title"><div className="modal-backdrop" onClick={onClose}/><div className="modal"><button className="modal-close" onClick={onClose} aria-label="Close"><X/></button><div className="modal-head"><WorkerIcon worker={worker} size="lg"/><div><Badge tone="green">Available for demo</Badge><h2 id="worker-title">{worker.name}</h2><p>{worker.description}</p></div></div><div className="modal-grid"><div><h4>Example tasks</h4><ul className="check-list">{worker.tasks.map(t=><li key={t}><Check/>{t}</li>)}</ul></div><div className="io-card"><div><small>TYPICAL INPUTS</small><p>{worker.inputs}</p></div><ArrowRight/><div><small>TYPICAL OUTPUTS</small><p>{worker.outputs}</p></div></div></div>{worker.id==='voice'&&<div className="process-row"><div><span>01</span><b>Voice input</b><small>Bangla or English</small></div><ChevronRight/><div><span>02</span><b>Process</b><small>Transcribe + classify</small></div><ChevronRight/><div><span>03</span><b>Human control</b><small>Operator approves</small></div></div>}<div className="recent"><h4><Activity/> Simulated recent activity</h4>{worker.activity.map(a=><p key={a}><CheckCircle2/>{a}<span>Demo data</span></p>)}</div><div className="modal-actions"><small><Users/> Human review remains required for external action.</small><button className="primary" onClick={onActivate}><Play/> Activate for demo</button></div></div></div>
}

function WorkersView({activate}:{activate:()=>void}) {const [selected,setSelected]=useState<Worker|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All workers');const groups:Record<string,WorkerId[]>={'All workers':workers.map(w=>w.id),'Operations':['voice','service','success'],'Growth':['growth','campaign','content'],'Experience':['landing','content','service']};const visible=workers.filter(w=>groups[filter].includes(w.id)&&(w.name+' '+w.description+' '+w.tags.join(' ')).toLowerCase().includes(query.toLowerCase()));return <div className="page"><SectionHeader eyebrow="AI WORKERS • 7 AVAILABLE" title="Specialists for every stage of growth." copy="Explore a coordinated workforce designed to handle focused tasks while keeping people in control."/><div className="filter-row"><div className="search-box"><Search/><input aria-label="Search workers" placeholder="Search capabilities" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-pills">{Object.keys(groups).map(g=><button key={g} className={filter===g?'active':''} onClick={()=>setFilter(g)}>{g}</button>)}</div></div><div className="workers-grid">{visible.map(w=><WorkerCard key={w.id} worker={w} onOpen={()=>setSelected(w)}/>)}</div>{visible.length===0&&<div className="empty-search"><Search/><b>No workers match that search.</b><button className="text-button" onClick={()=>{setQuery('');setFilter('All workers')}}>Clear filters</button></div>}<div className="trust-banner"><Users/><div><b>Human direction at every step</b><p>These workers prepare and recommend. Your team reviews consequential actions before anything moves forward.</p></div><Badge tone="cyan">Human in control</Badge></div>{selected&&<WorkerModal worker={selected} onClose={()=>setSelected(null)} onActivate={()=>{setSelected(null);activate()}}/>}</div>}

function WorkspaceCard({w,onOpen}:{w:typeof workspaces[number];onOpen:()=>void}) {return <article className="workspace-card"><div className="workspace-head"><span className="workspace-logo">{w.name.split(/\s/).map(x=>x[0]).join('').slice(0,2)}</span><Badge tone={w.status==='Active demo'?'green':'neutral'}>{w.status}</Badge></div><h3>{w.name}</h3><div className="workspace-meta"><span><BriefcaseBusiness/>{w.industry}</span><span><MapPin/>{w.location}</span></div><p className="objective"><small>OBJECTIVE</small>{w.objective}</p><div className="workspace-foot"><div className="avatar-stack">{w.active.map(id=><span key={id} style={{'--accent':getWorker(id).accent} as React.CSSProperties}>{getWorker(id).shortName[0]}</span>)}<small>{w.active.length} active workers</small></div><span>{w.activity} activities</span></div><button className="card-button" onClick={onOpen}>Open Workspace <ArrowRight/></button></article>}

function WorkspacesView({openClean}:{openClean:()=>void}) {const [selected,setSelected]=useState<number|null>(null);return <div className="page"><SectionHeader eyebrow="DEMO WORKSPACES" title="Organizations, challenges, and coordinated teams." copy="Fictional workspaces show how the AI workforce could be configured for different Bangladesh contexts." action={<Badge tone="amber">Illustrative demo data</Badge>}/><div className="workspace-grid">{workspaces.map((w,i)=><WorkspaceCard key={w.name} w={w} onOpen={i===0?openClean:()=>setSelected(i)}/>)}</div><div className="info-note"><CircleDot/><div><b>About these workspaces</b><p>Every organization, activity count, and outcome shown is fictional prototype content—not a customer claim.</p></div></div>{selected!==null&&<div className="modal-wrap"><div className="modal-backdrop" onClick={()=>setSelected(null)}/><div className="modal small-modal"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><Badge tone="purple">Concept demo workspace</Badge><h2>{workspaces[selected].name}</h2><p>{workspaces[selected].objective}</p><div className="concept-team"><small>PROPOSED AI WORKFORCE</small><div>{workspaces[selected].active.map(id=><span key={id}><WorkerIcon worker={getWorker(id)} size="sm"/>{getWorker(id).shortName}</span>)}</div></div><div className="coming"><Sparkles/><b>Lightweight concept preview</b><small>The full workflow is planned for a future prototype. No real activity is implied.</small></div></div></div>}</div>}

function ActivityTimeline({step,running}:{step:number;running:boolean}) {return <div className="timeline">{cleanDhakaActivity.map(([id,text],i)=>{const w=getWorker(id);const done=i<step;const active=running&&i===step;return <div className={`timeline-item ${done?'done':''} ${active?'active':''}`} key={id}><div className="timeline-line"/><WorkerIcon worker={w} size="sm"/><div className="timeline-copy"><div><b>{w.name}</b>{done?<Badge tone={i>3?'amber':'green'}>{i>3?'Needs approval':'Completed'}</Badge>:active?<Badge tone="cyan">Processing</Badge>:<Badge>Queued</Badge>}</div><p>{text}</p><small>{done?'Prepared in simulated workflow':active?'Analyzing demo input…':'Waiting for prior step'}</small></div></div>})}</div>}

function CleanDhaka({back}:{back:()=>void}) {
  const [step,setStep]=useState(0),[running,setRunning]=useState(false),[approved,setApproved]=useState(false),[editing,setEditing]=useState(false)
  useEffect(()=>{if(!running)return;if(step>=cleanDhakaActivity.length){setRunning(false);return}const t=setTimeout(()=>setStep(s=>s+1),650);return()=>clearTimeout(t)},[running,step])
  const run=()=>{setApproved(false);setStep(0);setRunning(true)};const reset=()=>{setStep(0);setRunning(false);setApproved(false);setEditing(false)}
  return <div className="page workspace-page"><button className="back-link" onClick={back}>← Demo Workspaces</button><SectionHeader eyebrow="ACTIVE DEMO WORKSPACE • SIMULATED" title="CleanDhaka AI Response Hub" copy="A simulated coordinated AI workforce for neighborhood waste-service response in Dhaka." action={<Badge tone="green">Demo running locally</Badge>}/><div className="scenario-banner"><span><MessageSquareText/></span><div><small>DEMO SCENARIO</small><b>A resident reports that waste has not been collected for three days.</b></div><Badge tone="amber">Human review required</Badge></div>
    <div className="investor-tooltip"><Sparkles/><p><b>Investor lens:</b> This demo illustrates the workflow architecture. Production impact must be validated with a real pilot.</p><Badge tone="cyan">Demo evidence only</Badge></div>
    <section className="value-bridge"><div><small>USER PROBLEM</small><b>Residents cannot easily report or track missed collection.</b></div><ArrowRight/><div><small>WORKFLOW BOTTLENECK</small><b>Manual intake, routing, and inconsistent follow-up.</b></div><ArrowRight/><div><small>AI INTERVENTION</small><b>Structure, classify, analyze, and draft next actions.</b></div><ArrowRight/><div><small>HUMAN DECISION</small><b>Coordinator verifies schedule and approves response.</b></div><ArrowRight/><div><small>OPERATIONAL VALUE</small><b>A clearer queue and repeatable response workflow.</b></div></section>
    <div className="pilot-value"><div><small>BUSINESS / INSTITUTIONAL VALUE • HYPOTHESIS</small><p>Potentially reduce repetitive coordination work while improving service visibility and operator accountability.</p></div><div><small>METRIC TO VALIDATE IN A PILOT</small><p>Time to triage, time to approved response, resolution rate, repeat complaints, and operator time per issue.</p></div></div>
    <div className="workspace-layout"><div className="main-column"><section className="panel issue-panel"><div className="panel-title"><div><span>01</span><div><h2>Issue intake</h2><p>Structured from a simulated voice transcript</p></div></div><Badge tone="purple">Voice transcript</Badge></div><blockquote>“The waste has not been collected from our lane for three days. The bin is overflowing and residents are worried about the smell.”</blockquote><div className="issue-grid">{[['Language','Bangla → English'],['Location','Mirpur, Dhaka'],['Urgency','Medium-high'],['Category','Missed collection']].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div><div className="status-row"><span><CircleDot/>Status</span><Badge tone="amber">Awaiting operator approval</Badge><button className="primary" onClick={run} disabled={running}><Play/>{running?'Workforce running…':step===7?'Run again':'Run AI Workforce'}</button></div></section>
      <section className="panel"><div className="panel-title"><div><span>02</span><div><h2>Coordinated activity</h2><p>Workers activate in sequence using demo data</p></div></div><span className="progress-label">{step} / 7 complete</span></div><div className="progress-track"><span style={{width:`${step/7*100}%`}}/></div><ActivityTimeline step={step} running={running}/></section></div>
      <aside className="right-column"><section className={`panel recommendation ${approved?'approved':''}`}><div className="panel-title"><div><span>03</span><div><h2>Recommended action</h2><p>Prepared for operator review</p></div></div></div>{approved&&<div className="approved-banner"><CheckCircle2/><b>Recommendation approved</b><small>Local demo state only—nothing was sent.</small></div>}<div className="recommend-meta"><div><small>PRIORITY</small><Badge tone="amber">Medium-high</Badge></div><div><small>RECOMMENDED OWNER</small><b>Local collection coordinator</b></div><div><small>NEXT STEP</small><b>Confirm pickup schedule</b></div></div><div className="response-box"><div><span>EN</span><small>SUGGESTED RESPONSE • ENGLISH</small></div>{editing?<textarea defaultValue="Thank you for reporting this issue. Your missed-collection report for Mirpur has been logged and marked for coordinator review. We will update the service status after confirmation."/>:<p>Thank you for reporting this issue. Your missed-collection report for Mirpur has been logged and marked for coordinator review. We will update the service status after confirmation.</p>}</div><div className="response-box bangla"><div><span>বাং</span><small>প্রস্তাবিত উত্তর • বাংলা</small></div><p>সমস্যাটি জানানোর জন্য ধন্যবাদ। মিরপুর এলাকার বর্জ্য সংগ্রহ না হওয়ার অভিযোগটি নথিভুক্ত করা হয়েছে এবং সমন্বয়কারীর পর্যালোচনার জন্য পাঠানো হয়েছে। নিশ্চিত হওয়ার পর আমরা সেবার অবস্থা জানাব।</p></div><div className="human-check"><Users/><div><b>Human approval required: Yes</b><small>Review content and service status before use.</small></div></div><div className="recommend-actions"><button className="primary" onClick={()=>setApproved(true)} disabled={approved||step<7}><Check/>{approved?'Approved':'Approve recommendation'}</button><button className="secondary" onClick={()=>setEditing(v=>!v)}><PenLine/>{editing?'Save edit':'Edit response'}</button><button className="reset-btn" onClick={reset}><RotateCcw/>Reset demo</button></div></section></aside></div>
    <section className="impact-section"><SectionHeader eyebrow="PROTOTYPE IMPACT" title="A clearer view of service response." copy="Sample metrics for prototype demonstration only."/><div className="metrics-grid">{metrics.map(([val,label,pct],i)=><article key={label}><div><span className="metric-icon">{i===2?<Activity/>:i===3?<TrendingUp/>:i===4?<Users/>:<BarChart3/>}</span><Badge>Demo metric</Badge></div><strong>{val}</strong><p>{label}</p><div className="metric-bar"><span style={{width:`${pct}%`}}/></div><small>{i===2?'Prototype service benchmark':'Simulated reporting period'}</small></article>)}</div></section>
  </div>
}

function ImpactView({openDemo}:{openDemo:()=>void}) {const [selected,setSelected]=useState<number|null>(null);return <div className="page"><SectionHeader eyebrow="BANGLADESH IMPACT • PROTOTYPE EXPLORER" title="Real Bangladesh problems. Coordinated AI workers. Local impact." copy="Explore responsible potential applications—not claims of deployed or proven outcomes."/><div className="impact-hero"><div><Globe2/><span>6</span><p>prototype opportunity areas</p></div><div><Users/><span>Human-centered</span><p>people review consequential actions</p></div><div><MapPin/><span>Bangladesh</span><p>local language and context</p></div></div><div className="problem-grid">{problems.map((p,i)=><article className={p.ready?'featured-problem':''} key={p.title}>{p.ready&&<div className="featured-label">FULLY DEVELOPED DEMO</div>}<div className="problem-no">0{i+1}</div><h3>{p.title}</h3><div className="problem-detail"><small>WHO IS AFFECTED</small><p>{p.affected}</p><small>EXAMPLE LOCATION</small><p><MapPin/>{p.location}</p><small>RELEVANT WORKERS</small><div className="mini-icons">{p.workerIds.map(id=><WorkerIcon key={id} worker={getWorker(id)} size="sm"/>)}</div><small>POTENTIAL HUMAN OUTCOME</small><p>{p.outcome}</p></div><button className={p.ready?'primary':'card-button'} onClick={()=>p.ready?openDemo():setSelected(i)}>{p.ready?'View simulated solution':'View concept'}<ArrowRight/></button></article>)}</div>{selected!==null&&<div className="modal-wrap"><div className="modal-backdrop" onClick={()=>setSelected(null)}/><div className="modal small-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><Badge tone="purple">Prototype concept</Badge><h2>{problems[selected].title}</h2><p>This potential application is planned for a future prototype. It would coordinate {problems[selected].workerIds.map(id=>getWorker(id).shortName).join(', ')} workers with human oversight.</p><div className="coming"><Sparkles/><b>Coming in the next prototype</b><small>No deployment or real-world outcome is claimed.</small></div></div></div>}</div>}

function TutorialView() {const [form,setForm]=useState(tutorialDefaults),[show,setShow]=useState(false);const fields:[keyof typeof form,string][]=[['organization','Organization name'],['type','Organization type'],['location','Location in Bangladesh'],['problem','Main problem'],['users','Target users'],['language','Preferred language'],['channel','Current communication channel'],['goal','Main goal']];return <div className="page tutorial-page"><SectionHeader eyebrow="WORKFORCE TUTORIAL • GUIDED SETUP" title="Teach your AI workforce about a new organization." copy="Describe the organization and its main challenge. The prototype will recommend which AI workers could help."/><div className="tutorial-layout"><form className="panel tutorial-form" onSubmit={e=>{e.preventDefault();setShow(true)}}><div className="form-head"><span>01</span><div><h2>Organization profile</h2><p>Pre-filled with sample CleanDhaka information.</p></div><button type="button" className="text-button" onClick={()=>{setForm(tutorialDefaults);setShow(false)}}><RotateCcw/> Try sample problem</button></div><div className="form-grid">{fields.map(([key,label])=><label key={key} className={key==='problem'||key==='goal'?'wide':''}><span>{label}</span>{key==='problem'||key==='goal'?<textarea value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div><div className="form-foot"><small><CircleDot/> Your information stays in this local frontend demo.</small><button className="primary" type="submit"><Sparkles/>Recommend AI Workforce</button></div></form><section className={`panel recommendation-result ${show?'show':''}`}><div className="form-head"><span>02</span><div><h2>Recommended team</h2><p>A simulated fit based on your profile.</p></div></div>{!show?<div className="empty-result"><span><Bot/></span><h3>Your workforce will appear here</h3><p>Complete the organization profile and generate a simulated recommendation.</p></div>:<><div className="result-summary"><Badge tone="cyan">6 workers recommended</Badge><h3>Built for service, communication, and learning.</h3><p>For <b>{form.organization||'your organization'}</b> in {form.location||'Bangladesh'}.</p></div><div className="recommend-list">{tutorialRecommendation.map(([id,reason],i)=>{const w=getWorker(id);return <div key={id}><span className="result-no">0{i+1}</span><WorkerIcon worker={w} size="sm"/><div><b>{w.name}</b><small>{reason}</small></div><CheckCircle2/></div>})}</div><p className="simulation-note"><Sparkles/>The recommendation is based on the organization’s communication, service, and growth needs. This is a simulated frontend result.</p></>}</section></div></div>}

type PitchField = 'market'|'traction'|'pilots'|'starter'|'growth'|'enterprise'|'interviews'|'activePilots'|'timeSaved'|'revenue'|'ask'|'milestone1'|'milestone2'|'milestone3'
const pitchDefaults:Record<PitchField,string>={market:'[INSERT VERIFIED MARKET DATA]',traction:'[INSERT VERIFIED TRACTION]',pilots:'[INSERT VERIFIED PILOTS]',starter:'[INSERT MONTHLY PRICE]',growth:'[INSERT MONTHLY PRICE]',enterprise:'[INSERT PRICING LOGIC]',interviews:'Not yet validated',activePilots:'Not yet validated',timeSaved:'Not yet validated',revenue:'Not yet validated',ask:'[INSERT FUNDING / PILOT / PARTNERSHIP ASK]',milestone1:'[INSERT MILESTONE 1]',milestone2:'[INSERT MILESTONE 2]',milestone3:'[INSERT MILESTONE 3]'}

function EditableField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="editable-field"><span>{label}<small>EDITABLE</small></span><input value={value} onChange={e=>onChange(e.target.value)} aria-label={label}/></label>}

function InvestorView({openDemo}:{openDemo:()=>void}){
  const [fields,setFields]=useState(pitchDefaults),[pitchStep,setPitchStep]=useState<number|null>(()=>{const saved=sessionStorage.getItem('pitchStep');return saved===null?null:Number(saved)})
  useEffect(()=>{if(pitchStep===null)sessionStorage.removeItem('pitchStep');else sessionStorage.setItem('pitchStep',String(pitchStep))},[pitchStep])
  const update=(key:PitchField,value:string)=>setFields({...fields,[key]:value})
  const steps=['Problem','Buyer & user','Product thesis','Live demo','Why we win','Business model','Proof','Roadmap','Ask']
  const show=(n:number)=>pitchStep===null||pitchStep===n
  const next=()=>setPitchStep(s=>s===null?0:Math.min(s+1,8))
  return <div className={`page investor-page ${pitchStep!==null?'presenting':''}`}>
    <SectionHeader eyebrow="INVESTOR VIEW • PLANNING NARRATIVE" title="An operating layer for AI-powered work." copy="Organizations do not need another chatbot. They need reliable AI workers that complete business workflows." action={<button className="primary" onClick={()=>{setPitchStep(0);window.scrollTo({top:0,behavior:'smooth'})}}><Play/>Start Pitch</button>}/>
    <div className="pitch-disclaimer"><ShieldCheck/><div><b>Credible by design</b><p>Product thesis, prototype evidence, and roadmap are labeled separately. Editable placeholders must be replaced with verified founder data.</p></div><Badge tone="amber">No fabricated traction</Badge></div>
    {pitchStep!==null&&<div className="pitch-nav"><button onClick={()=>setPitchStep(null)}><X/> Exit presentation</button><div>{steps.map((s,i)=><button key={s} className={pitchStep===i?'active':''} onClick={()=>setPitchStep(i)}><span>{i+1}</span>{s}</button>)}</div><span>{pitchStep+1} / {steps.length}</span></div>}

    {show(0)&&<section className="pitch-section opportunity"><div className="pitch-kicker">01 • THE OPPORTUNITY</div><h2>Repetitive service work breaks across disconnected people, inboxes, and tools.</h2><div className="opportunity-grid"><article><Workflow/><small>OPERATIONAL PROBLEM</small><b>High-volume communication becomes manual triage, inconsistent follow-up, and limited visibility.</b></article><article><Users/><small>WHO EXPERIENCES IT</small><b>Service teams, operators, and the people waiting for a response.</b></article><article><Layers3/><small>WHY TOOLS FALL SHORT</small><b>Chatbots answer; point tools store. Neither owns the coordinated handoff end to end.</b></article><article><Zap/><small>WHY NOW</small><b>Better language models and interfaces make specialized, supervised workflows practical to prototype.</b></article></div><div className="founder-inputs"><EditableField label="Target market size" value={fields.market} onChange={v=>update('market',v)}/><EditableField label="Current traction" value={fields.traction} onChange={v=>update('traction',v)}/><EditableField label="Pilot organizations" value={fields.pilots} onChange={v=>update('pilots',v)}/></div></section>}

    {show(1)&&<section className="pitch-section"><div className="pitch-kicker">02 • BUYER AND USER</div><h2>Start where communication volume and service accountability meet.</h2><div className="buyer-grid"><article><span><DollarSign/></span><small>ECONOMIC BUYER</small><h3>Operations or service leaders</h3><p>Organizations responsible for service cost, response quality, team capacity, and reporting.</p></article><article><span><UserRoundCheck/></span><small>PRIMARY USER</small><h3>Operators and coordinators</h3><p>People who review issues, approve responses, route work, and handle exceptions.</p></article><article><span><Users/></span><small>END BENEFICIARY</small><h3>Customers and communities</h3><p>People seeking accessible, timely, and consistent service—often across Bangla and English.</p></article></div><div className="beachhead"><div><Badge tone="cyan">Bangladesh beachhead</Badge><h3>High-volume communication and service workflows</h3><p>Waste management, agriculture support, local commerce, and community services provide focused contexts for workflow validation.</p></div><div className="expansion-path">{['One workflow for one organization','Multiple workflows for the same organization','Repeatable templates across similar organizations','Multi-organization platform with integrations and analytics'].map((s,i)=><div key={s}><span>{i+1}</span><p>{s}</p>{i<3&&<ChevronRight/>}</div>)}</div><div className="gtm-strip"><small>INITIAL GO-TO-MARKET HYPOTHESIS</small>{['Founder-led discovery with service organizations','One narrow, measurable pilot workflow','Convert learning into repeatable sector templates'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div></section>}

    {show(2)&&<section className="pitch-section"><div className="pitch-kicker">03 • PRODUCT THESIS</div><h2>Shared context, specialized execution, accountable decisions.</h2><div className="thesis-flow">{[['Business context','Channels, knowledge, workflows'],['Coordinated AI workers','Assign focused work'],['Human-approved action','Review important decisions'],['Measured outcome','Learn from workflow results']].map(([a,b],i)=><div key={a}><span>{i+1}</span><b>{a}</b><small>{b}</small>{i<3&&<ArrowRight/>}</div>)}</div><div className="thesis-points">{[['Connect','Connect the organization’s channels, knowledge, and workflows.'],['Assign','Assign work to specialized AI workers with shared context.'],['Govern','Route important actions through human approval and measure outcomes.']].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>}

    {show(3)&&<section className="pitch-section demo-bridge"><div><div className="pitch-kicker">04 • LIVE CLEANDHAKA WORKFLOW</div><h2>From resident complaint to a prepared, bilingual response.</h2><p>The prototype demonstrates intake, classification, trend review, follow-up planning, content preparation, and a mandatory operator approval point.</p><div className="demo-proof"><span><CheckCircle2/>Built: frontend workflow prototype</span><span><CheckCircle2/>Demonstrated: simulated CleanDhaka case</span><span><CircleDot/>Not claimed: production impact</span></div><button className="primary" onClick={openDemo}><Play/>Open live workflow</button></div><div className="demo-architecture"><small>SIMULATED ARCHITECTURE</small>{['Voice intake','Specialist coordination','Human approval','Pilot metric'].map((s,i)=><div key={s}><span>0{i+1}</span><b>{s}</b>{i<3&&<ChevronRight/>}</div>)}</div></section>}

    {show(4)&&<section className="pitch-section"><div className="pitch-kicker">05 • WHY A WORKFORCE, NOT A CHATBOT</div><h2>Coordination is the product thesis.</h2><div className="comparison-table"><div className="table-row table-head"><span>Alternative</span><span>Common limitation</span><span>AI Workforce Hub thesis</span></div>{[['Manual employees','Costly and inconsistent for repetitive work','Automate repeatable tasks; keep people on exceptions'],['Single chatbot','Handles conversation, not complete workflows','Specialists coordinate across functions'],['Separate SaaS tools','Fragmented context and disconnected handoffs','Shared context and one activity trail'],['Custom automation','Slow to build and maintain','Reusable worker capabilities and configurable workflows']].map(r=><div className="table-row" key={r[0]}>{r.map((c,i)=><span key={c}>{i===0&&<CircleDot/>}{c}</span>)}</div>)}</div><p className="careful-note">Competitive framing is a product thesis for validation—not independently verified benchmark data.</p></section>}

    {show(5)&&<section className="pitch-section"><div className="pitch-kicker">06 • BUSINESS MODEL PLACEHOLDER</div><h2>Subscription aligned with workflow volume and governance needs.</h2><div className="pricing-grid">{([['Starter','starter','For one focused workflow'],['Growth','growth','For multiple teams and workflows'],['Enterprise / custom','enterprise','For integrations and governance']] as [string,PitchField,string][]).map(([name,key,desc])=><article key={name}><small>{name.toUpperCase()}</small><EditableField label="Planning price" value={fields[key]} onChange={v=>update(key,v)}/><p>{desc}</p>{['Coordinated workers','Human approval','Activity visibility'].map(x=><span key={x}><Check/>{x}</span>)}</article>)}</div><div className="pricing-logic"><DollarSign/><p><b>Intended pricing logic:</b> Subscription plus usage or workflow volume, with higher tiers for integrations, governance, analytics, and custom workers.</p><Badge tone="amber">Planning placeholder</Badge></div></section>}

    {show(6)&&<section className="pitch-section"><div className="pitch-kicker">07 • PROOF AND VALIDATION</div><h2>Be precise about what exists—and what must be learned.</h2><div className="proof-states"><article className="built"><CheckCircle2/><small>BUILT</small><h3>Frontend workflow prototype</h3><p>Seven-worker directory, staged coordination, operator approval, and demo analytics.</p></article><article className="shown"><Play/><small>DEMONSTRATED</small><h3>Simulated CleanDhaka case</h3><p>A repeatable 3–5 minute workflow using fictional organization data.</p></article><article className="validate"><Target/><small>TO VALIDATE</small><h3>Real desirability and outcomes</h3><p>Interviews, pilot use, retention, time saved, resolution rate, and willingness to pay.</p></article></div><div className="validation-fields"><EditableField label="Customer interviews" value={fields.interviews} onChange={v=>update('interviews',v)}/><EditableField label="Active pilots" value={fields.activePilots} onChange={v=>update('activePilots',v)}/><EditableField label="Time saved" value={fields.timeSaved} onChange={v=>update('timeSaved',v)}/><EditableField label="Revenue" value={fields.revenue} onChange={v=>update('revenue',v)}/></div><div className="trust-grid"><div><ShieldCheck/><h3>Trust architecture</h3><p>Human approval and an agent activity trail are visible today. Confidence indicators, permissions, privacy controls, and uncertainty escalation belong in the pilot roadmap.</p></div>{[['Current','Human approval for consequential actions'],['Current','Visible simulated agent activity trail'],['Next','Confidence and uncertainty indicators'],['Roadmap','Role-based permissions'],['Roadmap','Data minimization and privacy controls'],['Next','Escalation when the AI is uncertain']].map(([state,text])=><span key={text}><Badge tone={state==='Current'?'green':state==='Next'?'cyan':'purple'}>{state}</Badge>{text}</span>)}</div></section>}

    {show(7)&&<section className="pitch-section"><div className="pitch-kicker">08 • ROADMAP</div><h2>Move from a credible demo to measured, governed deployment.</h2><div className="roadmap-grid">{[['NOW — MVP','Current capability',['Worker directory','Simulated coordinated workflow','Human approval states','Demo analytics']],['NEXT — PILOT','Validation plan',['Real organization onboarding','Channel integrations','Bangla voice and text evaluation','Workflow logs and outcome measurement']],['LATER — PLATFORM','Roadmap',['Configurable worker templates','Governance and permissions','Multi-tenant deployment','Usage analytics and billing']]].map(([stage,label,items],i)=><article key={stage as string} className={`roadmap-${i}`}><div><span>0{i+1}</span><Badge tone={i===0?'green':i===1?'cyan':'purple'}>{label as string}</Badge></div><h3>{stage as string}</h3>{(items as string[]).map(item=><p key={item}><Check/>{item}</p>)}</article>)}</div></section>}

    {show(8)&&<section className="pitch-section ask-section"><div className="pitch-kicker">09 • THE ASK</div><div className="ask-card"><Rocket/><Badge tone="purple">Founder input required</Badge><h2>Help us turn the workflow thesis into validated evidence.</h2><p>We are seeking</p><EditableField label="Funding, pilot, or partnership ask" value={fields.ask} onChange={v=>update('ask',v)}/><p>to validate the first workflows, onboard pilot organizations, and build the integration and governance layer.</p><div className="milestones">{(['milestone1','milestone2','milestone3'] as PitchField[]).map((key,i)=><div key={key}><span>{i+1}</span><EditableField label={`Milestone ${i+1}`} value={fields[key]} onChange={v=>update(key,v)}/></div>)}</div></div></section>}

    {pitchStep!==null&&<div className="pitch-controls"><button className="secondary" onClick={()=>setPitchStep(s=>Math.max(0,(s??0)-1))} disabled={pitchStep===0}>Previous</button><span>{steps[pitchStep]}</span>{pitchStep<8?<button className="primary" onClick={next}>Next: {steps[pitchStep+1]} <ArrowRight/></button>:<button className="primary" onClick={()=>setPitchStep(null)}><Check/>Finish pitch</button>}</div>}
  </div>
}

export default function App(){const [view,setView]=useState<View>('overview'),[menu,setMenu]=useState(false),[workspaceReturn,setWorkspaceReturn]=useState<View>('workspaces');const go=(v:View)=>{if(v==='workspace')setWorkspaceReturn(view);setView(v);window.scrollTo({top:0,behavior:'smooth'})};const content=useMemo(()=>{switch(view){case'overview':return <Overview go={go}/>;case'workers':return <WorkersView activate={()=>go('workspace')}/>;case'workspaces':return <WorkspacesView openClean={()=>go('workspace')}/>;case'workspace':return <CleanDhaka back={()=>go(workspaceReturn)}/>;case'impact':return <ImpactView openDemo={()=>go('workspace')}/>;case'tutorial':return <TutorialView/>;case'investor':return <InvestorView openDemo={()=>go('workspace')}/>}},[view,workspaceReturn]);return <div className="app"><Sidebar view={view} setView={go} open={menu} setOpen={setMenu}/><div className="app-main"><TopBar setMenu={setMenu}/><main>{content}</main><footer>Prototype showcase: organizations, activities, and metrics are illustrative demo content. <span>AI Workforce Hub © 2026</span></footer></div></div>}
